extend type Query {
  postList: [Posts]
  post(id: Int!): Posts
}

extend type Mutation {
  createPost(data: PostInput): Boolean
  updatePost(id: Int!, data: PostInput): Boolean
  deletePost(id: Int!): Boolean
}

type Posts {
  title: String
  content: String
  category_id: Int
  user_id: Int
}

input PostInput {
  title: String
  content: String
  category_id: Int
  user_id: Int
}
